AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantStructKeywordInit:
  Enabled: false
